"""
Clean, single-file implementation for sending weekly operational report.
Reads aggregated CSVs from `output/{week_name}/` directory (generated by data_pipeline.py).

The weekly report aggregates data across the entire week and provides
insights into trends, anomalies, and overall performance.

Usage:
    python send_weekly_report.py --week "week_1_september_2025" --dry-run
    python send_weekly_report.py --week "week_1_september_2025" --discord-only
    python send_weekly_report.py --week "week_1_september_2025" --gmail-only

Dependencies: pandas, requests
"""
from __future__ import annotations

import argparse
import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import List

import pandas as pd
import requests


# ---------------------------------------------------------------------------
# Config: filenames (look in `output/{week_name}/` folder)
# ---------------------------------------------------------------------------
BASE_DIR = Path(__file__).parent
OUTPUT_BASE_DIR = BASE_DIR / "output"
FILES = {
    "trips_per_day": "trips_per_day.csv",
    "revenue_per_day": "revenue_per_day.csv",
    "peak_hour_per_day": "peak_hour_per_day.csv",
    "daily_avg_metrics": "daily_avg_metrics.csv",
    "anomaly_monitoring": "anomaly_monitoring.csv",
}

# Discord webhook (from environment or hardcoded)
DISCORD_WEBHOOK_URL = os.getenv(
    "DISCORD_WEBHOOK_URL",
    "https://discord.com/api/webhooks/1439257051548352672/"
    "RRd5p75dHGq1Ory0_RYv8V9ERJ0YyfjOyscUViXJ3VzxQ-3a8vAyK9sdGKfYsqsYbLnD"
)

# Gmail SMTP Configuration (from environment or defaults)
GMAIL_SMTP_SERVER = os.getenv("GMAIL_SMTP_SERVER", "smtp.gmail.com")
GMAIL_SMTP_PORT = int(os.getenv("GMAIL_SMTP_PORT", "587"))
GMAIL_SENDER_EMAIL = os.getenv("GMAIL_SENDER_EMAIL", "buditriatmojo01@gmail.com")
GMAIL_SENDER_PASSWORD = os.getenv("GMAIL_SENDER_PASSWORD", "efaoyerhbaztlzep")
GMAIL_RECIPIENT_EMAILS = os.getenv(
    "GMAIL_RECIPIENT_EMAILS",
    "buditriatmojo01@gmail.com,adeliesly1501@gmail.com,samsudiney@gmail.com"
).split(",")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _parse_week_name_to_prefix(week_name: str) -> str:
    """
    Parse week_name to generate filename prefix.
    Input: "week_1_september_2025"
    Output: "2025_09_week1"
    """
    import re
    from datetime import datetime

    pattern = r'week_(\d+)_(\w+)_(\d{4})'
    match = re.match(pattern, week_name)

    if not match:
        return week_name.replace("_", "-")

    week_num = match.group(1)
    month_name = match.group(2)
    year = match.group(3)

    # Convert month name to number
    try:
        month_obj = datetime.strptime(month_name, "%B")
        month_num = f"{month_obj.month:02d}"
    except:
        month_obj = datetime.strptime(month_name.capitalize(), "%B")
        month_num = f"{month_obj.month:02d}"

    return f"{year}_{month_num}_week{week_num}"


def _find_csv_in_week_folder(week_name: str, metric_name: str) -> Path:
    """Find CSV in week-specific folder: output/{week_name}/{YYYY_MM_weekN_metric}.csv.
    Accepts either a direct CSV file or Spark-style output folder with part-*.csv.
    Returns full path to CSV file.
    """
    week_dir = OUTPUT_BASE_DIR / week_name
    prefix = _parse_week_name_to_prefix(week_name)
    filename = f"{prefix}_{metric_name}"

    candidate = week_dir / filename

    # If file exists directly
    if candidate.exists() and candidate.is_file():
        return candidate
    # If folder exists (spark output), look for part-*.csv
    if candidate.exists() and candidate.is_dir():
        parts = sorted(candidate.glob("part-*.csv"))
        if parts:
            return parts[0]

    # No file found
    raise FileNotFoundError(
        f"Tidak menemukan file CSV '{filename}' di folder week '{week_dir}'"
    )


def load_csv_with_validation(path: Path, required_columns: List[str]) -> pd.DataFrame:
    """Load CSV and validate required columns. Raises with clear messages."""
    try:
        df = pd.read_csv(path)
    except Exception as e:
        raise RuntimeError(f"Gagal membaca CSV {path}: {e}")

    # Normalize common column names FIRST before validation
    rename_map = {}
    if "pickup_date" in df.columns and "date" not in df.columns:
        rename_map["pickup_date"] = "date"
    if "trips_per_day" in df.columns and "total_trips" not in df.columns:
        rename_map["trips_per_day"] = "total_trips"
    if "revenue_per_day" in df.columns and "total_revenue" not in df.columns and "total_revenue_per_day" not in df.columns:
        rename_map["revenue_per_day"] = "total_revenue"
    if "avg_rev_per_trip" in df.columns and "avg_revenue_per_trip" not in df.columns:
        rename_map["avg_rev_per_trip"] = "avg_revenue_per_trip"

    if rename_map:
        df = df.rename(columns=rename_map)

    # Now validate required columns
    missing = [c for c in required_columns if c not in df.columns]
    if missing:
        raise ValueError(f"File {path.name} tidak mengandung kolom required: {missing}\nKolom yang ada: {list(df.columns)}")

    if "date" in df.columns:
        try:
            df["date"] = pd.to_datetime(df["date"]).dt.date
        except Exception:
            pass

    return df


def _fmt_int(x) -> str:
    try:
        return f"{int(x):,}"
    except Exception:
        return str(x)


def _fmt_money(x) -> str:
    try:
        return f"${float(x):,.2f}"
    except Exception:
        return str(x)


def parse_week_name(week_name: str) -> dict:
    """Parse week name like 'week_1_september_2025' to extract components."""
    parts = week_name.split("_")
    if len(parts) >= 4 and parts[0] == "week":
        return {
            "week_num": parts[1],
            "month": parts[2].capitalize(),
            "year": parts[3]
        }
    return {"week_num": "?", "month": "Unknown", "year": "?"}


def build_weekly_report_message(
    df_trips: pd.DataFrame,
    df_revenue: pd.DataFrame,
    df_peak: pd.DataFrame,
    df_metrics: pd.DataFrame,
    df_anomaly: pd.DataFrame,
    week_name: str,
) -> str:
    """Compose the Indonesian weekly report message (formal, concise)."""

    week_info = parse_week_name(week_name)
    week_display = f"Week {week_info['week_num']}, {week_info['month']} {week_info['year']}"

    # Calculate weekly totals (aggregate all data)
    total_trips = int(df_trips["total_trips"].sum()) if ("total_trips" in df_trips.columns and not df_trips.empty) else 0

    # Use total_revenue_per_day if available, else total_revenue
    revenue_col = "total_revenue_per_day" if "total_revenue_per_day" in df_revenue.columns else "total_revenue"
    total_revenue = float(df_revenue[revenue_col].sum()) if (revenue_col in df_revenue.columns and not df_revenue.empty) else 0.0

    # Calculate daily average
    num_days = len(df_trips["date"].unique()) if "date" in df_trips.columns and not df_trips.empty else 1
    daily_avg_trips = total_trips / num_days if num_days > 0 else 0
    daily_avg_revenue = total_revenue / num_days if num_days > 0 else 0.0

    # Peak hours: group by pickup_hour across the entire week
    peak_hours = None
    if "pickup_hour" in df_peak.columns and not df_peak.empty:
        # Aggregate trips by hour and find top 3
        peak_by_hour = df_peak.groupby("pickup_hour")["trips_per_hour"].sum().sort_values(ascending=False).head(3)
        if not peak_by_hour.empty:
            peak_hours = ", ".join([f"{int(h)}:00" for h in peak_by_hour.index])

    # Weekly average metrics
    avg_rev_trip = None
    avg_passengers = None
    if "avg_total_amount" in df_metrics.columns and not df_metrics.empty:
        try:
            # Calculate average across all days
            avg_rev_trip = float(df_metrics["avg_total_amount"].mean())
        except Exception:
            avg_rev_trip = None
    if "avg_passenger_count" in df_metrics.columns and not df_metrics.empty:
        try:
            avg_passengers = float(df_metrics["avg_passenger_count"].mean())
        except Exception:
            avg_passengers = None

    # Anomalies - aggregate across the week
    anomalies = []
    total_anomaly_count = 0
    if not df_anomaly.empty and "is_anomaly" in df_anomaly.columns:
        anomaly_rows = df_anomaly[df_anomaly["is_anomaly"] == True]
        total_anomaly_count = len(anomaly_rows)

        # Group by date to show which days had anomalies
        if "date" in anomaly_rows.columns:
            anomaly_by_date = anomaly_rows.groupby("date").size()
            for date, count in anomaly_by_date.head(5).items():
                anomalies.append(f"{date}: {count} anomali terdeteksi")
            if len(anomaly_by_date) > 5:
                anomalies.append(f"...dan {len(anomaly_by_date) - 5} hari lainnya")

    # Best and worst performing days
    best_day = None
    worst_day = None
    if "date" in df_revenue.columns and revenue_col in df_revenue.columns and not df_revenue.empty:
        # Group by date and sum revenue
        revenue_by_date = df_revenue.groupby("date")[revenue_col].sum().sort_values(ascending=False)
        if len(revenue_by_date) > 0:
            best_day = f"{revenue_by_date.index[0]} ({_fmt_money(revenue_by_date.iloc[0])})"
            worst_day = f"{revenue_by_date.index[-1]} ({_fmt_money(revenue_by_date.iloc[-1])})"

    # Build message
    header = f"📊 NYC Taxi Data Pipeline - Weekly Report — {week_display}"
    intro = (
        "Laporan ringkas performa mingguan layanan. Berikut ringkasan metrik utama, "
        "tren, dan temuan yang perlu menjadi perhatian tim operasi dan monitoring."
    )

    lines: List[str] = [header, "", intro, "", "**Ringkasan Mingguan**"]
    lines.append(f"• Total perjalanan (trips): **{_fmt_int(total_trips)}**")
    lines.append(f"• Total omzet: **{_fmt_money(total_revenue)}**")
    lines.append(f"• Rata‑rata perjalanan per hari: **{_fmt_int(daily_avg_trips)}**")
    lines.append(f"• Rata‑rata omzet per hari: **{_fmt_money(daily_avg_revenue)}**")
    if avg_rev_trip is not None:
        lines.append(f"• Rata‑rata omzet per trip: **{_fmt_money(avg_rev_trip)}**")
    if avg_passengers is not None:
        lines.append(f"• Rata‑rata penumpang per trip: **{avg_passengers:.2f}**")
    lines.append("")

    lines.append("**Jam Puncak Mingguan**")
    lines.append(f"• Jam puncak (3 teratas): **{peak_hours or 'data tidak tersedia'}**")
    lines.append("")

    lines.append("**Performa Harian**")
    if best_day:
        lines.append(f"• Hari terbaik: **{best_day}**")
    if worst_day:
        lines.append(f"• Hari terburuk: **{worst_day}**")
    lines.append(f"• Jumlah hari dengan data: **{num_days} hari**")
    lines.append("")

    lines.append("**Temuan Anomali Mingguan**")
    if total_anomaly_count > 0:
        lines.append(f"• Total anomali terdeteksi: **{total_anomaly_count}**")
        lines.append(f"• Hari dengan anomali:")
        for reason in anomalies:
            lines.append(f"  - {reason}")
    else:
        lines.append("• Tidak ada anomali signifikan terdeteksi minggu ini.")

    lines.append("")
    lines.append("**Rekomendasi & Tindakan**")
    if total_anomaly_count > 0:
        lines.append("• Review anomali yang terdeteksi untuk identifikasi pola atau masalah sistemik.")
        lines.append("• Evaluasi faktor penyebab pada hari-hari dengan anomali tinggi.")
        lines.append("• Koordinasikan dengan tim operasional untuk mitigasi di minggu mendatang.")
    else:
        lines.append("• Performa stabil sepanjang minggu. Pertahankan standar operasi saat ini.")
        lines.append("• Lanjutkan pemantauan harian, terutama pada jam puncak yang telah diidentifikasi.")

    lines.append("")
    lines.append(f"_Periode: {week_display}_")
    lines.append("_Dilaporkan oleh: Tim Operasional Data — Sistem Monitoring Otomatis_")

    return "\n".join(lines)


def send_to_discord(webhook_url: str, message: str) -> None:
    """Kirim pesan ke Discord via webhook sederhana (plain content)."""
    # Tambahkan mention untuk user samsudinde
    mention_message = f"<@samsudinde>\n{message}"
    payload = {"content": mention_message}
    try:
        resp = requests.post(webhook_url, json=payload, timeout=10)
    except requests.RequestException as e:
        raise RuntimeError(f"Gagal mengirim ke Discord: {e}")
    if resp.status_code not in (200, 204):
        raise RuntimeError(f"Discord returned status {resp.status_code}: {resp.text}")


def send_to_gmail(
    sender_email: str,
    sender_password: str,
    recipient_emails: List[str],
    subject: str,
    message: str,
    smtp_server: str = GMAIL_SMTP_SERVER,
    smtp_port: int = GMAIL_SMTP_PORT,
) -> None:
    """Kirim email via Gmail SMTP dengan format HTML dan plain text."""

    # Buat email message
    msg = MIMEMultipart("alternative")
    msg["From"] = sender_email
    msg["To"] = ", ".join(recipient_emails)
    msg["Subject"] = subject

    # Convert markdown-style message ke HTML sederhana
    html_message = message.replace("\n", "<br>")
    html_message = html_message.replace("**", "<strong>").replace("**", "</strong>")
    html_message = html_message.replace("_", "<em>").replace("_", "</em>")

    # Tambahkan styling untuk email
    html_body = f"""
    <html>
    <head>
        <style>
            body {{
                font-family: Arial, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
            }}
            h1 {{
                color: #2c3e50;
                border-bottom: 2px solid #3498db;
                padding-bottom: 10px;
            }}
            .metric {{
                background-color: #f8f9fa;
                padding: 15px;
                margin: 10px 0;
                border-left: 4px solid #3498db;
            }}
            .anomaly {{
                background-color: #fff3cd;
                padding: 15px;
                margin: 10px 0;
                border-left: 4px solid #ffc107;
            }}
            .footer {{
                margin-top: 30px;
                padding-top: 15px;
                border-top: 1px solid #ddd;
                font-size: 0.9em;
                color: #777;
            }}
        </style>
    </head>
    <body>
        <div class="metric">
            {html_message}
        </div>
    </body>
    </html>
    """

    # Attach plain text dan HTML versions
    part1 = MIMEText(message, "plain")
    part2 = MIMEText(html_body, "html")
    msg.attach(part1)
    msg.attach(part2)

    # Kirim email via SMTP
    try:
        # Remove spaces from password (App passwords biasanya tanpa spasi)
        clean_password = sender_password.replace(" ", "")

        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()  # Enable TLS encryption
            server.login(sender_email, clean_password)
            server.send_message(msg)
    except smtplib.SMTPAuthenticationError as e:
        raise RuntimeError(
            f"Gagal autentikasi Gmail: {e}\n"
            "Pastikan:\n"
            "1. Email dan password benar\n"
            "2. Menggunakan App Password (bukan password Gmail biasa)\n"
            "3. 2-Step Verification sudah aktif di akun Gmail\n"
            "4. App Password dibuat di: https://myaccount.google.com/apppasswords"
        )
    except smtplib.SMTPException as e:
        raise RuntimeError(f"Gagal mengirim email via SMTP: {e}")
    except Exception as e:
        raise RuntimeError(f"Error tidak terduga saat mengirim email: {e}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Kirim laporan mingguan ke Discord dan/atau Gmail")
    parser.add_argument(
        "--week",
        required=True,
        help="Nama minggu (contoh: week_1_september_2025)"
    )
    parser.add_argument("--dry-run", action="store_true", help="Jangan kirim; hanya tampilkan pesan")
    parser.add_argument("--discord-only", action="store_true", help="Kirim hanya ke Discord")
    parser.add_argument("--gmail-only", action="store_true", help="Kirim hanya ke Gmail")
    args = parser.parse_args()

    week_name = args.week

    # Determine send targets
    send_discord = not args.gmail_only
    send_gmail = not args.discord_only

    # Muat dan validasi file dari output/{week_name}/
    try:
        p_trips = _find_csv_in_week_folder(week_name, FILES["trips_per_day"])
        p_revenue = _find_csv_in_week_folder(week_name, FILES["revenue_per_day"])
        p_peak = _find_csv_in_week_folder(week_name, FILES["peak_hour_per_day"])
        p_metrics = _find_csv_in_week_folder(week_name, FILES["daily_avg_metrics"])
        p_anom = _find_csv_in_week_folder(week_name, FILES["anomaly_monitoring"])

        df_trips = load_csv_with_validation(p_trips, ["date", "total_trips"])
        df_revenue = load_csv_with_validation(p_revenue, ["date", "total_revenue_per_day"])
        df_peak = load_csv_with_validation(p_peak, ["date", "pickup_hour", "trips_per_hour"])
        df_metrics = load_csv_with_validation(p_metrics, ["date", "avg_total_amount"])
        df_anomaly = load_csv_with_validation(p_anom, ["date", "is_anomaly", "total_revenue_per_day"])
    except Exception as e:
        print(f"Error saat memuat file input: {e}")
        return

    try:
        message = build_weekly_report_message(
            df_trips=df_trips,
            df_revenue=df_revenue,
            df_peak=df_peak,
            df_metrics=df_metrics,
            df_anomaly=df_anomaly,
            week_name=week_name,
        )
    except Exception as e:
        print(f"Gagal membangun pesan laporan: {e}")
        return

    if args.dry_run:
        print("--- DRY RUN: pesan yang akan dikirim ---\n")
        print(f"Target: {'Discord' if send_discord else ''}{' & ' if (send_discord and send_gmail) else ''}{'Gmail' if send_gmail else ''}\n")
        print(message)
        print("\n--- END OF MESSAGE (dry-run) ---")
    else:
        success_count = 0
        errors = []

        # Send to Discord
        if send_discord:
            try:
                send_to_discord(DISCORD_WEBHOOK_URL, message)
                print("✓ Pesan berhasil dikirim ke Discord.")
                success_count += 1
            except Exception as e:
                error_msg = f"✗ Gagal mengirim ke Discord: {e}"
                print(error_msg)
                errors.append(error_msg)

        # Send to Gmail
        if send_gmail:
            try:
                week_info = parse_week_name(week_name)
                email_subject = f"NYC Taxi Data Pipeline - Weekly Report ({week_info['month']} {week_info['year']}, Week {week_info['week_num']})"
                send_to_gmail(
                    sender_email=GMAIL_SENDER_EMAIL,
                    sender_password=GMAIL_SENDER_PASSWORD,
                    recipient_emails=GMAIL_RECIPIENT_EMAILS,
                    subject=email_subject,
                    message=message,
                )
                print(f"✓ Email berhasil dikirim ke {len(GMAIL_RECIPIENT_EMAILS)} penerima:")
                for email in GMAIL_RECIPIENT_EMAILS:
                    print(f"  - {email}")
                success_count += 1
            except Exception as e:
                error_msg = f"✗ Gagal mengirim email: {e}"
                print(error_msg)
                errors.append(error_msg)

        # Summary
        print("\n" + "=" * 70)
        print(f"SUMMARY: {success_count} berhasil, {len(errors)} gagal")
        if errors:
            print("\nErrors:")
            for err in errors:
                print(f"  {err}")
        print("=" * 70)


if __name__ == "__main__":
    main()
