"""
Clean, single-file implementation for sending weekly operational report.
Reads aggregated CSVs from `output/{week_name}/` directory (generated by data_pipeline.py).

The weekly report aggregates data across the entire week and provides
insights into trends, anomalies, and overall performance.

Usage:
    python send_weekly_report.py --week "week_1_september_2025" --dry-run
    python send_weekly_report.py --week "week_1_september_2025" --discord-only
    python send_weekly_report.py --week "week_1_september_2025" --gmail-only

Dependencies: pandas, requests
"""
from __future__ import annotations

import argparse
import logging
import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from pathlib import Path
from typing import List

import pandas as pd
import requests


# ---------------------------------------------------------------------------
# Config: filenames (look in `output/{week_name}/` folder)
# ---------------------------------------------------------------------------
BASE_DIR = Path(__file__).parent
OUTPUT_BASE_DIR = BASE_DIR / "output"
LOG_FILE = BASE_DIR / "report.log"

FILES = {
    "trips_per_day": "trips_per_day.csv",
    "revenue_per_day": "revenue_per_day.csv",
    "peak_hour_per_day": "peak_hour_per_day.csv",
    "daily_avg_metrics": "daily_avg_metrics.csv",
    "anomaly_monitoring": "anomaly_monitoring.csv",
}


# ---------------------------------------------------------------------------
# Logging Configuration
# ---------------------------------------------------------------------------

def setup_logging():
    """Configure logging to write to both file and console."""
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - [WEEKLY_REPORT] - %(levelname)s - %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S',
        handlers=[
            logging.FileHandler(LOG_FILE, mode='a', encoding='utf-8'),
            logging.StreamHandler()
        ]
    )
    return logging.getLogger(__name__)

# Discord webhook (from environment or hardcoded)
DISCORD_WEBHOOK_URL = os.getenv(
    "DISCORD_WEBHOOK_URL",
    "https://discord.com/api/webhooks/1439257051548352672/"
    "RRd5p75dHGq1Ory0_RYv8V9ERJ0YyfjOyscUViXJ3VzxQ-3a8vAyK9sdGKfYsqsYbLnD"
)

# Gmail SMTP Configuration (from environment or defaults)
GMAIL_SMTP_SERVER = os.getenv("GMAIL_SMTP_SERVER", "smtp.gmail.com")
GMAIL_SMTP_PORT = int(os.getenv("GMAIL_SMTP_PORT", "587"))
GMAIL_SENDER_EMAIL = os.getenv("GMAIL_SENDER_EMAIL", "buditriatmojo01@gmail.com")
GMAIL_SENDER_PASSWORD = os.getenv("GMAIL_SENDER_PASSWORD", "efaoyerhbaztlzep")
GMAIL_RECIPIENT_EMAILS = os.getenv(
    "GMAIL_RECIPIENT_EMAILS",
    "buditriatmojo01@gmail.com,adeliesly1501@gmail.com,samsudiney@gmail.com"
).split(",")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _parse_week_name_to_prefix(week_name: str) -> str:
    """
    Parse week_name to generate filename prefix.
    Input: "week_1_september_2025"
    Output: "2025_09_week1"
    """
    import re
    from datetime import datetime

    pattern = r'week_(\d+)_(\w+)_(\d{4})'
    match = re.match(pattern, week_name)

    if not match:
        return week_name.replace("_", "-")

    week_num = match.group(1)
    month_name = match.group(2)
    year = match.group(3)

    # Convert month name to number
    try:
        month_obj = datetime.strptime(month_name, "%B")
        month_num = f"{month_obj.month:02d}"
    except:
        month_obj = datetime.strptime(month_name.capitalize(), "%B")
        month_num = f"{month_obj.month:02d}"

    return f"{year}_{month_num}_week{week_num}"


def _find_csv_in_week_folder(week_name: str, metric_name: str) -> Path:
    """Find CSV in week-specific folder: output/{week_name}/{YYYY_MM_weekN_metric}.csv.
    Accepts either a direct CSV file or Spark-style output folder with part-*.csv.
    Returns full path to CSV file.
    """
    week_dir = OUTPUT_BASE_DIR / week_name
    prefix = _parse_week_name_to_prefix(week_name)
    filename = f"{prefix}_{metric_name}"

    candidate = week_dir / filename

    # If file exists directly
    if candidate.exists() and candidate.is_file():
        return candidate
    # If folder exists (spark output), look for part-*.csv
    if candidate.exists() and candidate.is_dir():
        parts = sorted(candidate.glob("part-*.csv"))
        if parts:
            return parts[0]

    # No file found
    raise FileNotFoundError(
        f"Tidak menemukan file CSV '{filename}' di folder week '{week_dir}'"
    )


def load_csv_with_validation(path: Path, required_columns: List[str]) -> pd.DataFrame:
    """Load CSV and validate required columns. Raises with clear messages."""
    try:
        df = pd.read_csv(path)
    except Exception as e:
        raise RuntimeError(f"Gagal membaca CSV {path}: {e}")

    # Normalize common column names FIRST before validation
    rename_map = {}
    if "pickup_date" in df.columns and "date" not in df.columns:
        rename_map["pickup_date"] = "date"
    if "trips_per_day" in df.columns and "total_trips" not in df.columns:
        rename_map["trips_per_day"] = "total_trips"
    if "revenue_per_day" in df.columns and "total_revenue" not in df.columns and "total_revenue_per_day" not in df.columns:
        rename_map["revenue_per_day"] = "total_revenue"
    if "avg_rev_per_trip" in df.columns and "avg_revenue_per_trip" not in df.columns:
        rename_map["avg_rev_per_trip"] = "avg_revenue_per_trip"

    if rename_map:
        df = df.rename(columns=rename_map)

    # Now validate required columns
    missing = [c for c in required_columns if c not in df.columns]
    if missing:
        raise ValueError(f"File {path.name} tidak mengandung kolom required: {missing}\nKolom yang ada: {list(df.columns)}")

    if "date" in df.columns:
        try:
            df["date"] = pd.to_datetime(df["date"]).dt.date
        except Exception:
            pass

    return df


def _fmt_int(x) -> str:
    try:
        return f"{int(x):,}"
    except Exception:
        return str(x)


def _fmt_money(x) -> str:
    try:
        return f"${float(x):,.2f}"
    except Exception:
        return str(x)


def parse_week_name(week_name: str) -> dict:
    """Parse week name like 'week_1_september_2025' to extract components."""
    parts = week_name.split("_")
    if len(parts) >= 4 and parts[0] == "week":
        return {
            "week_num": parts[1],
            "month": parts[2].capitalize(),
            "year": parts[3]
        }
    return {"week_num": "?", "month": "Unknown", "year": "?"}


def build_weekly_report_message(
    df_trips: pd.DataFrame,
    df_revenue: pd.DataFrame,
    df_peak: pd.DataFrame,
    df_metrics: pd.DataFrame,
    df_anomaly: pd.DataFrame,
    week_name: str,
    for_discord: bool = False,
) -> str:
    """Compose the formal weekly report message with structured data aggregation.

    Args:
        for_discord: If True, formats message for Discord with detailed aggregation data
    """

    week_info = parse_week_name(week_name)
    week_display = f"Minggu ke-{week_info['week_num']}, {week_info['month']} {week_info['year']}"

    # Calculate weekly totals (aggregate all data)
    total_trips = int(df_trips["total_trips"].sum()) if ("total_trips" in df_trips.columns and not df_trips.empty) else 0

    # Use total_revenue_per_day if available, else total_revenue
    revenue_col = "total_revenue_per_day" if "total_revenue_per_day" in df_revenue.columns else "total_revenue"
    total_revenue = float(df_revenue[revenue_col].sum()) if (revenue_col in df_revenue.columns and not df_revenue.empty) else 0.0

    # Calculate daily average
    num_days = len(df_trips["date"].unique()) if "date" in df_trips.columns and not df_trips.empty else 1
    daily_avg_trips = total_trips / num_days if num_days > 0 else 0
    daily_avg_revenue = total_revenue / num_days if num_days > 0 else 0.0

    # Peak hours: group by pickup_hour across the entire week
    peak_hours = None
    if "pickup_hour" in df_peak.columns and not df_peak.empty:
        # Aggregate trips by hour and find top 3
        peak_by_hour = df_peak.groupby("pickup_hour")["trips_per_hour"].sum().sort_values(ascending=False).head(3)
        if not peak_by_hour.empty:
            peak_hours = ", ".join([f"{int(h)}:00" for h in peak_by_hour.index])

    # Weekly average metrics
    avg_rev_trip = None
    avg_passengers = None
    if "avg_total_amount" in df_metrics.columns and not df_metrics.empty:
        try:
            # Calculate average across all days
            avg_rev_trip = float(df_metrics["avg_total_amount"].mean())
        except Exception:
            avg_rev_trip = None
    if "avg_passenger_count" in df_metrics.columns and not df_metrics.empty:
        try:
            avg_passengers = float(df_metrics["avg_passenger_count"].mean())
        except Exception:
            avg_passengers = None

    # Anomalies - aggregate across the week
    anomalies = []
    total_anomaly_count = 0
    if not df_anomaly.empty and "is_anomaly" in df_anomaly.columns:
        anomaly_rows = df_anomaly[df_anomaly["is_anomaly"] == True]
        total_anomaly_count = len(anomaly_rows)

        # Group by date to show which days had anomalies
        if "date" in anomaly_rows.columns:
            anomaly_by_date = anomaly_rows.groupby("date").size()
            for date, count in anomaly_by_date.head(5).items():
                anomalies.append(f"{date}: {count} anomali terdeteksi")
            if len(anomaly_by_date) > 5:
                anomalies.append(f"...dan {len(anomaly_by_date) - 5} hari lainnya")

    # Best and worst performing days
    best_day = None
    worst_day = None
    if "date" in df_revenue.columns and revenue_col in df_revenue.columns and not df_revenue.empty:
        # Group by date and sum revenue
        revenue_by_date = df_revenue.groupby("date")[revenue_col].sum().sort_values(ascending=False)
        if len(revenue_by_date) > 0:
            best_day = f"{revenue_by_date.index[0]} ({_fmt_money(revenue_by_date.iloc[0])})"
            worst_day = f"{revenue_by_date.index[-1]} ({_fmt_money(revenue_by_date.iloc[-1])})"

    # Build message
    header = f"📊 LAPORAN MINGGUAN DATA TAKSI NYC — {week_display}"
    intro = (
        "Berikut adalah laporan komprehensif performa layanan taksi NYC untuk periode minggu ini. "
        "Laporan ini mencakup agregasi data perjalanan, pendapatan, dan analisis anomali yang telah diproses "
        "melalui pipeline data otomatis."
    )

    lines: List[str] = [header, "=" * 70, intro, ""]

    # Section 1: Summary Metrics
    lines.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    lines.append("📈 RINGKASAN METRIK MINGGUAN")
    lines.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    lines.append(f"• Total Perjalanan        : {_fmt_int(total_trips)} trips")
    lines.append(f"• Total Pendapatan        : {_fmt_money(total_revenue)}")
    lines.append(f"• Rata-rata Trip per Hari : {_fmt_int(daily_avg_trips)} trips/hari")
    lines.append(f"• Rata-rata Revenue/Hari  : {_fmt_money(daily_avg_revenue)}/hari")
    if avg_rev_trip is not None:
        lines.append(f"• Rata-rata Revenue/Trip  : {_fmt_money(avg_rev_trip)}/trip")
    if avg_passengers is not None:
        lines.append(f"• Rata-rata Penumpang     : {avg_passengers:.2f} orang/trip")
    lines.append(f"• Periode Pelaporan       : {num_days} hari")
    lines.append("")

    # Section 2: Detailed Data Aggregation (for Discord only)
    if for_discord:
        lines.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
        lines.append("📊 DATA AGREGASI HARIAN")
        lines.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")

        # Aggregate trips and revenue by date
        if "date" in df_trips.columns and not df_trips.empty:
            trips_by_date = df_trips.groupby("date")["total_trips"].sum()
            revenue_col = "total_revenue_per_day" if "total_revenue_per_day" in df_revenue.columns else "total_revenue"
            if "date" in df_revenue.columns and not df_revenue.empty:
                revenue_by_date = df_revenue.groupby("date")[revenue_col].sum()

                lines.append("```")
                lines.append(f"{'Tanggal':<12} {'Trips':>10} {'Pendapatan':>15}")
                lines.append("-" * 40)
                for date in sorted(trips_by_date.index):
                    trips = trips_by_date.get(date, 0)
                    revenue = revenue_by_date.get(date, 0)
                    lines.append(f"{str(date):<12} {_fmt_int(trips):>10} {_fmt_money(revenue):>15}")
                lines.append("```")
                lines.append("")

    # Section 3: Peak Hours Analysis
    lines.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    lines.append("⏰ ANALISIS JAM PUNCAK")
    lines.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    lines.append(f"• Jam Tersibuk (Top 3)    : {peak_hours or 'Data tidak tersedia'}")
    lines.append("")

    # Section 4: Performance Highlights
    lines.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    lines.append("🏆 HIGHLIGHT PERFORMA")
    lines.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    if best_day:
        lines.append(f"• Hari dengan Revenue Tertinggi  : {best_day}")
    if worst_day:
        lines.append(f"• Hari dengan Revenue Terendah   : {worst_day}")
    lines.append("")

    # Section 5: Anomaly Detection
    lines.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    lines.append("🔍 DETEKSI ANOMALI")
    lines.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    if total_anomaly_count > 0:
        lines.append(f"• Total Anomali Terdeteksi : {total_anomaly_count} kejadian")
        lines.append("")
        lines.append("Detail Anomali per Hari:")
        for reason in anomalies:
            lines.append(f"  • {reason}")
    else:
        lines.append("• Status: Tidak ada anomali signifikan terdeteksi pada periode ini.")
        lines.append("• Indikasi: Operasional berjalan normal dan stabil.")

    lines.append("")

    # Section 6: Recommendations
    lines.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    lines.append("💡 REKOMENDASI TINDAK LANJUT")
    lines.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    if total_anomaly_count > 0:
        lines.append("1. Lakukan review mendalam terhadap anomali yang teridentifikasi untuk")
        lines.append("   mendeteksi pola atau potensi masalah sistemik.")
        lines.append("2. Evaluasi faktor penyebab pada periode dengan anomali tinggi.")
        lines.append("3. Koordinasikan dengan tim operasional untuk implementasi mitigasi")
        lines.append("   pada minggu mendatang.")
    else:
        lines.append("1. Performa operasional menunjukkan stabilitas yang baik.")
        lines.append("2. Pertahankan standar operasi dan protokol yang telah berjalan.")
        lines.append("3. Lanjutkan pemantauan rutin, khususnya pada jam-jam puncak")
        lines.append("   yang telah teridentifikasi.")

    lines.append("")
    lines.append("=" * 70)
    lines.append(f"Periode Laporan  : {week_display}")
    lines.append(f"Tanggal Generate : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("Sistem Pelaporan : NYC Taxi Data Pipeline - Automated Monitoring")
    lines.append("=" * 70)

    return "\n".join(lines)


def build_email_message_with_csv_explanation(week_name: str) -> str:
    """Build formal email message explaining the aggregated data and CSV files."""
    week_info = parse_week_name(week_name)
    week_display = f"Minggu ke-{week_info['week_num']}, {week_info['month']} {week_info['year']}"

    message = f"""Kepada Yth. Tim Monitoring dan Analisis Data,

Dengan hormat,

Bersama email ini, kami sampaikan Laporan Agregasi Data Mingguan NYC Taxi Data Pipeline untuk periode {week_display}.

TUJUAN LAPORAN
==============
Laporan ini bertujuan untuk memberikan gambaran komprehensif mengenai performa operasional layanan taksi NYC berdasarkan data yang telah dikumpulkan dan diproses melalui sistem data pipeline otomatis. Analisis ini mencakup metrik kunci, tren performa, dan identifikasi anomali yang memerlukan perhatian.

PENJELASAN DATA AGREGASI
=========================

Terlampir pada email ini adalah file-file CSV yang berisi data agregasi mingguan sebagai berikut:

1. TRIPS_PER_DAY.CSV
   - Deskripsi: Agregasi jumlah perjalanan (trips) per hari
   - Kolom utama: date, taxi_type, total_trips
   - Kegunaan: Menganalisis volume perjalanan harian dan tren mobilitas
   - Insight: Membantu mengidentifikasi pola permintaan layanan taksi

2. REVENUE_PER_DAY.CSV
   - Deskripsi: Agregasi total pendapatan (revenue) per hari
   - Kolom utama: date, taxi_type, total_revenue_per_day
   - Kegunaan: Evaluasi performa finansial harian
   - Insight: Mengidentifikasi hari dengan pendapatan tertinggi/terendah

3. PEAK_HOUR_PER_DAY.CSV
   - Deskripsi: Analisis jam puncak berdasarkan volume perjalanan
   - Kolom utama: date, pickup_hour, trips_per_hour
   - Kegunaan: Identifikasi periode waktu dengan permintaan tertinggi
   - Insight: Optimasi alokasi armada dan strategi operasional

4. DAILY_AVG_METRICS.CSV
   - Deskripsi: Rata-rata metrik operasional harian
   - Kolom utama: date, avg_total_amount, avg_trip_distance,
                 avg_trip_duration, avg_passenger_count
   - Kegunaan: Evaluasi efisiensi operasional dan pengalaman pelanggan
   - Insight: Benchmark performa dan identifikasi area perbaikan

5. ANOMALY_MONITORING.CSV
   - Deskripsi: Deteksi dan monitoring anomali operasional
   - Kolom utama: date, is_anomaly, daily_trips, total_revenue_per_day,
                 avg_passenger_count
   - Kegunaan: Early warning system untuk deviasi operasional
   - Insight: Identifikasi masalah potensial yang memerlukan investigasi

METODOLOGI AGREGASI
====================
Data agregasi dihasilkan melalui proses sebagai berikut:
• Ekstraksi data mentah dari sumber NYC TLC (Taxi & Limousine Commission)
• Pembersihan dan validasi data menggunakan Apache PySpark
• Agregasi statistik berdasarkan dimensi waktu (hari, jam)
• Analisis anomali menggunakan metode statistik (±2σ deviation)
• Export hasil ke format CSV untuk kemudahan analisis lanjutan

REKOMENDASI PENGGUNAAN
======================
1. Gunakan file CSV terlampir untuk analisis mendalam dan visualisasi data
2. Fokuskan perhatian pada anomali yang teridentifikasi
3. Bandingkan metrik mingguan dengan periode sebelumnya untuk trend analysis
4. Koordinasikan temuan dengan tim operasional untuk action planning

Apabila terdapat pertanyaan atau memerlukan klarifikasi lebih lanjut mengenai data yang dilampirkan, silakan menghubungi tim data engineering.

Terima kasih atas perhatian dan kerjasamanya.

Hormat kami,

NYC Taxi Data Pipeline - Automated Monitoring System
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---
Catatan: Email ini digenerate secara otomatis oleh sistem. File CSV terlampir berisi data agregasi untuk periode {week_display}.
"""
    return message


def send_to_discord(webhook_url: str, message: str) -> None:
    """Kirim pesan ke Discord via webhook, split jika lebih dari 2000 karakter."""
    # Discord limit: 2000 characters per message
    MAX_LENGTH = 1900  # Leave some buffer

    # Tambahkan mention untuk user samsudinde di pesan pertama
    mention_message = f"<@samsudinde>\n{message}"

    # Split message jika terlalu panjang
    if len(mention_message) <= 2000:
        # Send as single message
        payload = {"content": mention_message}
        try:
            resp = requests.post(webhook_url, json=payload, timeout=10)
        except requests.RequestException as e:
            raise RuntimeError(f"Gagal mengirim ke Discord: {e}")
        if resp.status_code not in (200, 204):
            raise RuntimeError(f"Discord returned status {resp.status_code}: {resp.text}")
    else:
        # Split into multiple messages
        lines = mention_message.split('\n')
        chunks = []
        current_chunk = []
        current_length = 0

        for line in lines:
            line_length = len(line) + 1  # +1 for newline
            if current_length + line_length > MAX_LENGTH:
                # Save current chunk and start new one
                chunks.append('\n'.join(current_chunk))
                current_chunk = [line]
                current_length = line_length
            else:
                current_chunk.append(line)
                current_length += line_length

        # Add last chunk
        if current_chunk:
            chunks.append('\n'.join(current_chunk))

        # Send each chunk
        for i, chunk in enumerate(chunks):
            payload = {"content": chunk}
            try:
                resp = requests.post(webhook_url, json=payload, timeout=10)
            except requests.RequestException as e:
                raise RuntimeError(f"Gagal mengirim ke Discord (bagian {i+1}/{len(chunks)}): {e}")
            if resp.status_code not in (200, 204):
                raise RuntimeError(f"Discord returned status {resp.status_code} (bagian {i+1}/{len(chunks)}): {resp.text}")
            # Small delay between messages to avoid rate limiting
            if i < len(chunks) - 1:
                import time
                time.sleep(0.5)


def send_to_gmail(
    sender_email: str,
    sender_password: str,
    recipient_emails: List[str],
    subject: str,
    message: str,
    csv_attachments: List[Path] = None,
    smtp_server: str = GMAIL_SMTP_SERVER,
    smtp_port: int = GMAIL_SMTP_PORT,
) -> None:
    """Kirim email via Gmail SMTP dengan format HTML, plain text, dan CSV attachments.

    Args:
        csv_attachments: List of Path objects to CSV files to attach
    """

    # Buat email message
    msg = MIMEMultipart("mixed")
    msg["From"] = sender_email
    msg["To"] = ", ".join(recipient_emails)
    msg["Subject"] = subject

    # Convert markdown-style message ke HTML sederhana
    html_message = message.replace("\n", "<br>")
    html_message = html_message.replace("**", "<strong>").replace("**", "</strong>")
    html_message = html_message.replace("_", "<em>").replace("_", "</em>")

    # Tambahkan styling untuk email
    html_body = f"""
    <html>
    <head>
        <style>
            body {{
                font-family: Arial, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
            }}
            h1 {{
                color: #2c3e50;
                border-bottom: 2px solid #3498db;
                padding-bottom: 10px;
            }}
            .metric {{
                background-color: #f8f9fa;
                padding: 15px;
                margin: 10px 0;
                border-left: 4px solid #3498db;
            }}
            .anomaly {{
                background-color: #fff3cd;
                padding: 15px;
                margin: 10px 0;
                border-left: 4px solid #ffc107;
            }}
            .footer {{
                margin-top: 30px;
                padding-top: 15px;
                border-top: 1px solid #ddd;
                font-size: 0.9em;
                color: #777;
            }}
        </style>
    </head>
    <body>
        <div class="metric">
            {html_message}
        </div>
    </body>
    </html>
    """

    # Attach plain text dan HTML versions
    msg_body = MIMEMultipart("alternative")
    part1 = MIMEText(message, "plain")
    part2 = MIMEText(html_body, "html")
    msg_body.attach(part1)
    msg_body.attach(part2)
    msg.attach(msg_body)

    # Attach CSV files if provided
    if csv_attachments:
        for csv_path in csv_attachments:
            if csv_path.exists() and csv_path.is_file():
                with open(csv_path, "rb") as f:
                    part = MIMEBase("application", "octet-stream")
                    part.set_payload(f.read())
                    encoders.encode_base64(part)

                    # Use proper filename: if it's a part file from Spark output,
                    # use the parent directory name + .csv extension
                    if csv_path.name.startswith("part-"):
                        # This is a Spark output part file, use parent folder name
                        attachment_name = f"{csv_path.parent.name}.csv"
                    else:
                        # Use the actual filename
                        attachment_name = csv_path.name

                    part.add_header(
                        "Content-Disposition",
                        f"attachment; filename={attachment_name}",
                    )
                    msg.attach(part)

    # Kirim email via SMTP
    try:
        # Remove spaces from password (App passwords biasanya tanpa spasi)
        clean_password = sender_password.replace(" ", "")

        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()  # Enable TLS encryption
            server.login(sender_email, clean_password)
            server.send_message(msg)
    except smtplib.SMTPAuthenticationError as e:
        raise RuntimeError(
            f"Gagal autentikasi Gmail: {e}\n"
            "Pastikan:\n"
            "1. Email dan password benar\n"
            "2. Menggunakan App Password (bukan password Gmail biasa)\n"
            "3. 2-Step Verification sudah aktif di akun Gmail\n"
            "4. App Password dibuat di: https://myaccount.google.com/apppasswords"
        )
    except smtplib.SMTPException as e:
        raise RuntimeError(f"Gagal mengirim email via SMTP: {e}")
    except Exception as e:
        raise RuntimeError(f"Error tidak terduga saat mengirim email: {e}")


def main() -> None:
    # Setup logging
    logger = setup_logging()

    parser = argparse.ArgumentParser(description="Kirim laporan mingguan ke Discord dan/atau Gmail")
    parser.add_argument(
        "--week",
        required=True,
        help="Nama minggu (contoh: week_1_september_2025)"
    )
    parser.add_argument("--dry-run", action="store_true", help="Jangan kirim; hanya tampilkan pesan")
    parser.add_argument("--discord-only", action="store_true", help="Kirim hanya ke Discord")
    parser.add_argument("--gmail-only", action="store_true", help="Kirim hanya ke Gmail")
    args = parser.parse_args()

    week_name = args.week

    # Determine send targets
    send_discord = not args.gmail_only
    send_gmail = not args.discord_only

    logger.info("=" * 70)
    logger.info("WEEKLY REPORT SENDER - STARTED")
    logger.info("=" * 70)
    logger.info(f"Week: {week_name}")
    logger.info(f"Mode: {'DRY RUN' if args.dry_run else 'LIVE'}")
    logger.info(f"Targets: Discord={send_discord}, Gmail={send_gmail}")

    # Muat dan validasi file dari output/{week_name}/
    try:
        logger.info(f"Loading CSV files from output/{week_name}/")
        p_trips = _find_csv_in_week_folder(week_name, FILES["trips_per_day"])
        p_revenue = _find_csv_in_week_folder(week_name, FILES["revenue_per_day"])
        p_peak = _find_csv_in_week_folder(week_name, FILES["peak_hour_per_day"])
        p_metrics = _find_csv_in_week_folder(week_name, FILES["daily_avg_metrics"])
        p_anom = _find_csv_in_week_folder(week_name, FILES["anomaly_monitoring"])

        logger.info("Validating CSV data")
        df_trips = load_csv_with_validation(p_trips, ["date", "total_trips"])
        df_revenue = load_csv_with_validation(p_revenue, ["date", "total_revenue_per_day"])
        df_peak = load_csv_with_validation(p_peak, ["date", "pickup_hour", "trips_per_hour"])
        df_metrics = load_csv_with_validation(p_metrics, ["date", "avg_total_amount"])
        df_anomaly = load_csv_with_validation(p_anom, ["date", "is_anomaly", "total_revenue_per_day"])
        logger.info("All CSV files loaded and validated successfully")
    except Exception as e:
        logger.error(f"Failed to load CSV files: {e}", exc_info=True)
        print(f"Error saat memuat file input: {e}")
        return

    # Build messages
    try:
        logger.info("Building report messages")
        # Discord message with detailed aggregation data
        discord_message = build_weekly_report_message(
            df_trips=df_trips,
            df_revenue=df_revenue,
            df_peak=df_peak,
            df_metrics=df_metrics,
            df_anomaly=df_anomaly,
            week_name=week_name,
            for_discord=True,  # Include detailed aggregation tables
        )

        # Email message with CSV explanation
        email_message = build_email_message_with_csv_explanation(week_name)

        # Collect CSV file paths for email attachments
        csv_files = [p_trips, p_revenue, p_peak, p_metrics, p_anom]
        logger.info("Report messages built successfully")

    except Exception as e:
        logger.error(f"Failed to build report messages: {e}", exc_info=True)
        print(f"Gagal membangun pesan laporan: {e}")
        return

    if args.dry_run:
        logger.info("DRY RUN MODE - No messages will be sent")
        print("=" * 70)
        print("DRY RUN MODE - Preview Pesan yang Akan Dikirim")
        print("=" * 70)
        print(f"\nTarget: {'Discord' if send_discord else ''}{' & ' if (send_discord and send_gmail) else ''}{'Gmail' if send_gmail else ''}\n")

        if send_discord:
            print("\n" + "=" * 70)
            print("DISCORD MESSAGE PREVIEW")
            print("=" * 70)
            print(discord_message)

        if send_gmail:
            print("\n" + "=" * 70)
            print("EMAIL MESSAGE PREVIEW")
            print("=" * 70)
            print(email_message)
            print("\n" + "=" * 70)
            print("CSV ATTACHMENTS:")
            print("=" * 70)
            for csv_file in csv_files:
                # Show proper filename (same logic as attachment)
                if csv_file.name.startswith("part-"):
                    display_name = f"{csv_file.parent.name}.csv"
                else:
                    display_name = csv_file.name
                print(f"  • {display_name}")

        print("\n" + "=" * 70)
        print("END OF DRY RUN")
        print("=" * 70)
    else:
        success_count = 0
        errors = []

        # Send to Discord
        if send_discord:
            try:
                logger.info("Sending report to Discord")
                send_to_discord(DISCORD_WEBHOOK_URL, discord_message)
                msg_len = len(f"<@samsudinde>\n{discord_message}")
                if msg_len > 2000:
                    num_parts = (msg_len // 1900) + 1
                    logger.info(f"Discord message sent successfully ({num_parts} parts)")
                    print(f"✓ Pesan berhasil dikirim ke Discord ({num_parts} bagian) dengan data agregasi lengkap.")
                else:
                    logger.info("Discord message sent successfully")
                    print("✓ Pesan berhasil dikirim ke Discord dengan data agregasi lengkap.")
                success_count += 1
            except Exception as e:
                error_msg = f"✗ Gagal mengirim ke Discord: {e}"
                logger.error(f"Failed to send to Discord: {e}", exc_info=True)
                print(error_msg)
                errors.append(error_msg)

        # Send to Gmail
        if send_gmail:
            try:
                logger.info(f"Sending email with {len(csv_files)} CSV attachments to {len(GMAIL_RECIPIENT_EMAILS)} recipients")
                week_info = parse_week_name(week_name)
                email_subject = f"[NYC Taxi Pipeline] Laporan Agregasi Data Mingguan - {week_info['month']} {week_info['year']}, Minggu ke-{week_info['week_num']}"
                send_to_gmail(
                    sender_email=GMAIL_SENDER_EMAIL,
                    sender_password=GMAIL_SENDER_PASSWORD,
                    recipient_emails=GMAIL_RECIPIENT_EMAILS,
                    subject=email_subject,
                    message=email_message,
                    csv_attachments=csv_files,
                )
                logger.info(f"Email sent successfully to {GMAIL_RECIPIENT_EMAILS}")
                print(f"✓ Email dengan {len(csv_files)} file CSV berhasil dikirim ke {len(GMAIL_RECIPIENT_EMAILS)} penerima:")
                for email in GMAIL_RECIPIENT_EMAILS:
                    print(f"  - {email}")
                print(f"\nFile CSV yang dilampirkan:")
                for csv_file in csv_files:
                    # Show proper filename (same logic as attachment)
                    if csv_file.name.startswith("part-"):
                        display_name = f"{csv_file.parent.name}.csv"
                    else:
                        display_name = csv_file.name
                    print(f"  • {display_name}")
                success_count += 1
            except Exception as e:
                error_msg = f"✗ Gagal mengirim email: {e}"
                logger.error(f"Failed to send email: {e}", exc_info=True)
                print(error_msg)
                errors.append(error_msg)

        # Summary
        logger.info(f"Report sending completed: {success_count} successful, {len(errors)} failed")
        if errors:
            logger.error(f"Errors occurred: {errors}")
        logger.info("=" * 70)
        logger.info("WEEKLY REPORT SENDER - COMPLETED")
        logger.info("=" * 70)

        print("\n" + "=" * 70)
        print(f"SUMMARY: {success_count} berhasil, {len(errors)} gagal")
        if errors:
            print("\nErrors:")
            for err in errors:
                print(f"  {err}")
        print("=" * 70)


if __name__ == "__main__":
    main()
