"""
Clean, single-file implementation for sending weekly operational report.
Reads aggregated CSVs from `output/{week_name}/` directory (generated by data_pipeline.py).

The weekly report aggregates data across the entire week and provides
insights into trends, anomalies, and overall performance.

Usage:
    python send_weekly_report.py --week "week_1_september_2025" --dry-run
    python send_weekly_report.py --week "week_1_september_2025" --discord-only
    python send_weekly_report.py --week "week_1_september_2025" --gmail-only

Dependencies: pandas, requests
"""
from __future__ import annotations

import argparse
import logging
import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from pathlib import Path
from typing import List

import pandas as pd
import requests


# ---------------------------------------------------------------------------
# Config: filenames (look in `output/{week_name}/` folder)
# ---------------------------------------------------------------------------
BASE_DIR = Path(__file__).parent
OUTPUT_BASE_DIR = BASE_DIR / "output"
LOG_FILE = BASE_DIR / "report.log"

FILES = {
    "trips_per_day": "trips_per_day.csv",
    "revenue_per_day": "revenue_per_day.csv",
    "peak_hour_per_day": "peak_hour_per_day.csv",
    "daily_avg_metrics": "daily_avg_metrics.csv",
    "anomaly_monitoring": "anomaly_monitoring.csv",
}


# ---------------------------------------------------------------------------
# Logging Configuration
# ---------------------------------------------------------------------------

def setup_logging():
    """Configure logging to write to both file and console."""
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - [WEEKLY_REPORT] - %(levelname)s - %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S',
        handlers=[
            logging.FileHandler(LOG_FILE, mode='a', encoding='utf-8'),
            logging.StreamHandler()
        ]
    )
    return logging.getLogger(__name__)

# Discord webhook (from environment or hardcoded)
DISCORD_WEBHOOK_URL = os.getenv(
    "DISCORD_WEBHOOK_URL",
    "https://discord.com/api/webhooks/1439257051548352672/"
    "RRd5p75dHGq1Ory0_RYv8V9ERJ0YyfjOyscUViXJ3VzxQ-3a8vAyK9sdGKfYsqsYbLnD"
)

# Gmail SMTP Configuration (from environment or defaults)
GMAIL_SMTP_SERVER = os.getenv("GMAIL_SMTP_SERVER", "smtp.gmail.com")
GMAIL_SMTP_PORT = int(os.getenv("GMAIL_SMTP_PORT", "587"))
GMAIL_SENDER_EMAIL = os.getenv("GMAIL_SENDER_EMAIL", "buditriatmojo01@gmail.com")
GMAIL_SENDER_PASSWORD = os.getenv("GMAIL_SENDER_PASSWORD", "efaoyerhbaztlzep")
GMAIL_RECIPIENT_EMAILS = os.getenv(
    "GMAIL_RECIPIENT_EMAILS",
    "buditriatmojo01@gmail.com,adeliesly1501@gmail.com,samsudiney@gmail.com"
).split(",")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _parse_week_name_to_prefix(week_name: str) -> str:
    """
    Parse week_name to generate filename prefix.
    Input: "week_1_september_2025"
    Output: "2025_09_week1"
    """
    import re
    from datetime import datetime

    pattern = r'week_(\d+)_(\w+)_(\d{4})'
    match = re.match(pattern, week_name)

    if not match:
        return week_name.replace("_", "-")

    week_num = match.group(1)
    month_name = match.group(2)
    year = match.group(3)

    # Convert month name to number
    try:
        month_obj = datetime.strptime(month_name, "%B")
        month_num = f"{month_obj.month:02d}"
    except:
        month_obj = datetime.strptime(month_name.capitalize(), "%B")
        month_num = f"{month_obj.month:02d}"

    return f"{year}_{month_num}_week{week_num}"


def _find_csv_in_week_folder(week_name: str, metric_name: str) -> Path:
    """Find CSV in week-specific folder: output/{week_name}/{YYYY_MM_weekN_metric}.csv.
    Accepts either a direct CSV file or Spark-style output folder with part-*.csv.
    Returns full path to CSV file.
    """
    week_dir = OUTPUT_BASE_DIR / week_name
    prefix = _parse_week_name_to_prefix(week_name)
    filename = f"{prefix}_{metric_name}"

    candidate = week_dir / filename

    # If file exists directly
    if candidate.exists() and candidate.is_file():
        return candidate
    # If folder exists (spark output), look for part-*.csv
    if candidate.exists() and candidate.is_dir():
        parts = sorted(candidate.glob("part-*.csv"))
        if parts:
            return parts[0]

    # No file found
    raise FileNotFoundError(
        f"Tidak menemukan file CSV '{filename}' di folder week '{week_dir}'"
    )


def load_csv_with_validation(path: Path, required_columns: List[str]) -> pd.DataFrame:
    """Load CSV and validate required columns. Raises with clear messages."""
    try:
        df = pd.read_csv(path)
    except Exception as e:
        raise RuntimeError(f"Gagal membaca CSV {path}: {e}")

    # Normalize common column names FIRST before validation
    rename_map = {}
    if "pickup_date" in df.columns and "date" not in df.columns:
        rename_map["pickup_date"] = "date"
    if "trips_per_day" in df.columns and "total_trips" not in df.columns:
        rename_map["trips_per_day"] = "total_trips"
    if "revenue_per_day" in df.columns and "total_revenue" not in df.columns and "total_revenue_per_day" not in df.columns:
        rename_map["revenue_per_day"] = "total_revenue"
    if "avg_rev_per_trip" in df.columns and "avg_revenue_per_trip" not in df.columns:
        rename_map["avg_rev_per_trip"] = "avg_revenue_per_trip"

    if rename_map:
        df = df.rename(columns=rename_map)

    # Now validate required columns
    missing = [c for c in required_columns if c not in df.columns]
    if missing:
        raise ValueError(f"File {path.name} tidak mengandung kolom required: {missing}\nKolom yang ada: {list(df.columns)}")

    if "date" in df.columns:
        try:
            df["date"] = pd.to_datetime(df["date"]).dt.date
        except Exception:
            pass

    return df


def _fmt_int(x) -> str:
    try:
        return f"{int(x):,}"
    except Exception:
        return str(x)


def _fmt_money(x) -> str:
    try:
        return f"${float(x):,.2f}"
    except Exception:
        return str(x)


def parse_week_name(week_name: str) -> dict:
    """Parse week name like 'week_1_september_2025' to extract components."""
    parts = week_name.split("_")
    if len(parts) >= 4 and parts[0] == "week":
        return {
            "week_num": parts[1],
            "month": parts[2].capitalize(),
            "year": parts[3]
        }
    return {"week_num": "?", "month": "Unknown", "year": "?"}


def build_weekly_report_message(
    df_trips: pd.DataFrame,
    df_revenue: pd.DataFrame,
    df_peak: pd.DataFrame,
    df_metrics: pd.DataFrame,
    df_anomaly: pd.DataFrame,
    week_name: str,
    for_discord: bool = False,
) -> str:
    """Compose a clean, professional weekly report with key insights.

    Args:
        for_discord: If True, includes daily breakdown table
    """

    week_info = parse_week_name(week_name)
    week_display = f"Week {week_info['week_num']}, {week_info['month']} {week_info['year']}"

    # Calculate weekly totals
    total_trips = int(df_trips["total_trips"].sum()) if ("total_trips" in df_trips.columns and not df_trips.empty) else 0
    revenue_col = "total_revenue_per_day" if "total_revenue_per_day" in df_revenue.columns else "total_revenue"
    total_revenue = float(df_revenue[revenue_col].sum()) if (revenue_col in df_revenue.columns and not df_revenue.empty) else 0.0

    # Calculate averages
    num_days = len(df_trips["date"].unique()) if "date" in df_trips.columns and not df_trips.empty else 1
    daily_avg_trips = total_trips / num_days if num_days > 0 else 0
    daily_avg_revenue = total_revenue / num_days if num_days > 0 else 0.0

    # Peak hours analysis
    peak_hours = None
    if "pickup_hour" in df_peak.columns and not df_peak.empty:
        peak_by_hour = df_peak.groupby("pickup_hour")["trips_per_hour"].sum().sort_values(ascending=False).head(3)
        if not peak_by_hour.empty:
            peak_hours = ", ".join([f"{int(h)}:00" for h in peak_by_hour.index])

    # Trip metrics
    avg_rev_trip = None
    if "avg_total_amount" in df_metrics.columns and not df_metrics.empty:
        try:
            avg_rev_trip = float(df_metrics["avg_total_amount"].mean())
        except Exception:
            pass

    # Anomaly detection
    total_anomaly_count = 0
    if not df_anomaly.empty and "is_anomaly" in df_anomaly.columns:
        total_anomaly_count = len(df_anomaly[df_anomaly["is_anomaly"] == True])

    # Best/worst days
    best_day = None
    worst_day = None
    if "date" in df_revenue.columns and revenue_col in df_revenue.columns and not df_revenue.empty:
        revenue_by_date = df_revenue.groupby("date")[revenue_col].sum().sort_values(ascending=False)
        if len(revenue_by_date) > 0:
            best_day = f"{revenue_by_date.index[0]} ({_fmt_money(revenue_by_date.iloc[0])})"
            worst_day = f"{revenue_by_date.index[-1]} ({_fmt_money(revenue_by_date.iloc[-1])})"

    # Build message
    lines: List[str] = []
    lines.append("📊 **NYC TAXI WEEKLY REPORT**")
    lines.append(f"*{week_display}*")
    lines.append("")

    # Key Metrics
    lines.append("**📈 WEEKLY SUMMARY**")
    lines.append(f"• Total Trips: **{_fmt_int(total_trips)}**")
    lines.append(f"• Total Revenue: **{_fmt_money(total_revenue)}**")
    lines.append(f"• Daily Average: {_fmt_int(daily_avg_trips)} trips | {_fmt_money(daily_avg_revenue)}")
    if avg_rev_trip:
        lines.append(f"• Avg Revenue/Trip: {_fmt_money(avg_rev_trip)}")
    lines.append("")

    # Daily breakdown (Discord only)
    if for_discord and "date" in df_trips.columns and not df_trips.empty:
        lines.append("**📊 DAILY BREAKDOWN**")
        trips_by_date = df_trips.groupby("date")["total_trips"].sum()
        if "date" in df_revenue.columns and not df_revenue.empty:
            revenue_by_date = df_revenue.groupby("date")[revenue_col].sum()
            lines.append("```")
            lines.append(f"{'Date':<12} {'Trips':>10} {'Revenue':>15}")
            lines.append("-" * 40)
            for date in sorted(trips_by_date.index):
                trips = trips_by_date.get(date, 0)
                revenue = revenue_by_date.get(date, 0)
                lines.append(f"{str(date):<12} {_fmt_int(trips):>10} {_fmt_money(revenue):>15}")
            lines.append("```")
            lines.append("")

    # Performance insights
    lines.append("**🏆 PERFORMANCE HIGHLIGHTS**")
    if peak_hours:
        lines.append(f"• Busiest Hours: {peak_hours}")
    if best_day:
        lines.append(f"• Best Day: {best_day}")
    if worst_day:
        lines.append(f"• Lowest Day: {worst_day}")
    lines.append("")

    # Anomaly status
    lines.append("**🔍 STATUS**")
    if total_anomaly_count > 0:
        lines.append(f"⚠️ {total_anomaly_count} anomalies detected - review recommended")
    else:
        lines.append("✅ All metrics within normal range")
    lines.append("")

    # Footer
    lines.append("─" * 50)
    lines.append(f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | NYC Taxi Data Pipeline*")

    return "\n".join(lines)


def build_email_message_with_csv_explanation(week_name: str) -> str:
    """Build professional email message with CSV data explanation."""
    week_info = parse_week_name(week_name)
    week_display = f"Week {week_info['week_num']}, {week_info['month']} {week_info['year']}"

    message = f"""Dear Team,

Please find attached the NYC Taxi Weekly Data Report for {week_display}.

ATTACHED FILES
==============
This report includes 5 CSV files with aggregated metrics:

1. Trips Per Day - Daily trip volume by taxi type
2. Revenue Per Day - Daily revenue totals by taxi type
3. Peak Hour Analysis - Hourly trip distribution patterns
4. Daily Avg Metrics - Average trip metrics (distance, fare, duration, passengers)
5. Anomaly Monitoring - Statistical anomaly detection and alerts

KEY INSIGHTS
============
• The data covers {week_display} with comprehensive trip and revenue analysis
• Files are ready for import into Excel, Tableau, or other analytics tools
• Anomalies are flagged for operational review and action planning
• All metrics include date, taxi type, and relevant measurements

NEXT STEPS
==========
• Review the anomaly_monitoring.csv for any flagged issues
• Compare metrics with previous weeks to identify trends
• Use peak_hour data to optimize fleet allocation
• Share findings with operations team for strategic planning

For questions or additional analysis, please contact the data engineering team.

Best regards,

NYC Taxi Data Pipeline - Automated Reporting
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---
Note: This is an automated report. CSV files contain aggregated data for {week_display}.
"""
    return message


def send_to_discord(webhook_url: str, message: str) -> None:
    """Kirim pesan ke Discord via webhook, split jika lebih dari 2000 karakter."""
    # Discord limit: 2000 characters per message
    MAX_LENGTH = 1900  # Leave some buffer

    # Split message jika terlalu panjang
    if len(message) <= 2000:
        # Send as single message
        payload = {"content": message}
        try:
            resp = requests.post(webhook_url, json=payload, timeout=10)
        except requests.RequestException as e:
            raise RuntimeError(f"Gagal mengirim ke Discord: {e}")
        if resp.status_code not in (200, 204):
            raise RuntimeError(f"Discord returned status {resp.status_code}: {resp.text}")
    else:
        # Split into multiple messages
        lines = message.split('\n')
        chunks = []
        current_chunk = []
        current_length = 0

        for line in lines:
            line_length = len(line) + 1  # +1 for newline
            if current_length + line_length > MAX_LENGTH:
                # Save current chunk and start new one
                chunks.append('\n'.join(current_chunk))
                current_chunk = [line]
                current_length = line_length
            else:
                current_chunk.append(line)
                current_length += line_length

        # Add last chunk
        if current_chunk:
            chunks.append('\n'.join(current_chunk))

        # Send each chunk
        for i, chunk in enumerate(chunks):
            payload = {"content": chunk}
            try:
                resp = requests.post(webhook_url, json=payload, timeout=10)
            except requests.RequestException as e:
                raise RuntimeError(f"Gagal mengirim ke Discord (bagian {i+1}/{len(chunks)}): {e}")
            if resp.status_code not in (200, 204):
                raise RuntimeError(f"Discord returned status {resp.status_code} (bagian {i+1}/{len(chunks)}): {resp.text}")
            # Small delay between messages to avoid rate limiting
            if i < len(chunks) - 1:
                import time
                time.sleep(0.5)


def send_to_gmail(
    sender_email: str,
    sender_password: str,
    recipient_emails: List[str],
    subject: str,
    message: str,
    csv_attachments: List[Path] = None,
    smtp_server: str = GMAIL_SMTP_SERVER,
    smtp_port: int = GMAIL_SMTP_PORT,
) -> None:
    """Kirim email via Gmail SMTP dengan format HTML, plain text, dan CSV attachments.

    Args:
        csv_attachments: List of Path objects to CSV files to attach
    """

    # Buat email message
    msg = MIMEMultipart("mixed")
    msg["From"] = sender_email
    msg["To"] = ", ".join(recipient_emails)
    msg["Subject"] = subject

    # Convert markdown-style message ke HTML sederhana
    html_message = message.replace("\n", "<br>")
    html_message = html_message.replace("**", "<strong>").replace("**", "</strong>")
    html_message = html_message.replace("_", "<em>").replace("_", "</em>")

    # Tambahkan styling untuk email
    html_body = f"""
    <html>
    <head>
        <style>
            body {{
                font-family: Arial, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
            }}
            h1 {{
                color: #2c3e50;
                border-bottom: 2px solid #3498db;
                padding-bottom: 10px;
            }}
            .metric {{
                background-color: #f8f9fa;
                padding: 15px;
                margin: 10px 0;
                border-left: 4px solid #3498db;
            }}
            .anomaly {{
                background-color: #fff3cd;
                padding: 15px;
                margin: 10px 0;
                border-left: 4px solid #ffc107;
            }}
            .footer {{
                margin-top: 30px;
                padding-top: 15px;
                border-top: 1px solid #ddd;
                font-size: 0.9em;
                color: #777;
            }}
        </style>
    </head>
    <body>
        <div class="metric">
            {html_message}
        </div>
    </body>
    </html>
    """

    # Attach plain text dan HTML versions
    msg_body = MIMEMultipart("alternative")
    part1 = MIMEText(message, "plain")
    part2 = MIMEText(html_body, "html")
    msg_body.attach(part1)
    msg_body.attach(part2)
    msg.attach(msg_body)

    # Attach CSV files if provided
    if csv_attachments:
        for csv_path in csv_attachments:
            if csv_path.exists() and csv_path.is_file():
                with open(csv_path, "rb") as f:
                    part = MIMEBase("application", "octet-stream")
                    part.set_payload(f.read())
                    encoders.encode_base64(part)

                    # Use proper filename: if it's a part file from Spark output,
                    # use the parent directory name + .csv extension
                    if csv_path.name.startswith("part-"):
                        # This is a Spark output part file, use parent folder name
                        attachment_name = f"{csv_path.parent.name}.csv"
                    else:
                        # Use the actual filename
                        attachment_name = csv_path.name

                    part.add_header(
                        "Content-Disposition",
                        f"attachment; filename={attachment_name}",
                    )
                    msg.attach(part)

    # Kirim email via SMTP
    try:
        # Remove spaces from password (App passwords biasanya tanpa spasi)
        clean_password = sender_password.replace(" ", "")

        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()  # Enable TLS encryption
            server.login(sender_email, clean_password)
            server.send_message(msg)
    except smtplib.SMTPAuthenticationError as e:
        raise RuntimeError(
            f"Gagal autentikasi Gmail: {e}\n"
            "Pastikan:\n"
            "1. Email dan password benar\n"
            "2. Menggunakan App Password (bukan password Gmail biasa)\n"
            "3. 2-Step Verification sudah aktif di akun Gmail\n"
            "4. App Password dibuat di: https://myaccount.google.com/apppasswords"
        )
    except smtplib.SMTPException as e:
        raise RuntimeError(f"Gagal mengirim email via SMTP: {e}")
    except Exception as e:
        raise RuntimeError(f"Error tidak terduga saat mengirim email: {e}")


def main() -> None:
    # Setup logging
    logger = setup_logging()

    parser = argparse.ArgumentParser(description="Kirim laporan mingguan ke Discord dan/atau Gmail")
    parser.add_argument(
        "--week",
        required=True,
        help="Nama minggu (contoh: week_1_september_2025)"
    )
    parser.add_argument("--dry-run", action="store_true", help="Jangan kirim; hanya tampilkan pesan")
    parser.add_argument("--discord-only", action="store_true", help="Kirim hanya ke Discord")
    parser.add_argument("--gmail-only", action="store_true", help="Kirim hanya ke Gmail")
    args = parser.parse_args()

    week_name = args.week

    # Determine send targets
    send_discord = not args.gmail_only
    send_gmail = not args.discord_only

    logger.info("=" * 70)
    logger.info("WEEKLY REPORT SENDER - STARTED")
    logger.info("=" * 70)
    logger.info(f"Week: {week_name}")
    logger.info(f"Mode: {'DRY RUN' if args.dry_run else 'LIVE'}")
    logger.info(f"Targets: Discord={send_discord}, Gmail={send_gmail}")

    # Muat dan validasi file dari output/{week_name}/
    try:
        logger.info(f"Loading CSV files from output/{week_name}/")
        p_trips = _find_csv_in_week_folder(week_name, FILES["trips_per_day"])
        p_revenue = _find_csv_in_week_folder(week_name, FILES["revenue_per_day"])
        p_peak = _find_csv_in_week_folder(week_name, FILES["peak_hour_per_day"])
        p_metrics = _find_csv_in_week_folder(week_name, FILES["daily_avg_metrics"])
        p_anom = _find_csv_in_week_folder(week_name, FILES["anomaly_monitoring"])

        logger.info("Validating CSV data")
        df_trips = load_csv_with_validation(p_trips, ["date", "total_trips"])
        df_revenue = load_csv_with_validation(p_revenue, ["date", "total_revenue_per_day"])
        df_peak = load_csv_with_validation(p_peak, ["date", "pickup_hour", "trips_per_hour"])
        df_metrics = load_csv_with_validation(p_metrics, ["date", "avg_total_amount"])
        df_anomaly = load_csv_with_validation(p_anom, ["date", "is_anomaly", "total_revenue_per_day"])
        logger.info("All CSV files loaded and validated successfully")
    except Exception as e:
        logger.error(f"Failed to load CSV files: {e}", exc_info=True)
        print(f"Error saat memuat file input: {e}")
        return

    # Build messages
    try:
        logger.info("Building report messages")
        # Discord message with detailed aggregation data
        discord_message = build_weekly_report_message(
            df_trips=df_trips,
            df_revenue=df_revenue,
            df_peak=df_peak,
            df_metrics=df_metrics,
            df_anomaly=df_anomaly,
            week_name=week_name,
            for_discord=True,  # Include detailed aggregation tables
        )

        # Email message - use same format as Discord (without detailed daily breakdown)
        email_message = build_weekly_report_message(
            df_trips=df_trips,
            df_revenue=df_revenue,
            df_peak=df_peak,
            df_metrics=df_metrics,
            df_anomaly=df_anomaly,
            week_name=week_name,
            for_discord=False,  # Don't include detailed daily breakdown in email
        )

        # Collect CSV file paths for email attachments
        csv_files = [p_trips, p_revenue, p_peak, p_metrics, p_anom]
        logger.info("Report messages built successfully")

    except Exception as e:
        logger.error(f"Failed to build report messages: {e}", exc_info=True)
        print(f"Gagal membangun pesan laporan: {e}")
        return

    if args.dry_run:
        logger.info("DRY RUN MODE - No messages will be sent")
        print("=" * 70)
        print("DRY RUN MODE - Preview Pesan yang Akan Dikirim")
        print("=" * 70)
        print(f"\nTarget: {'Discord' if send_discord else ''}{' & ' if (send_discord and send_gmail) else ''}{'Gmail' if send_gmail else ''}\n")

        if send_discord:
            print("\n" + "=" * 70)
            print("DISCORD MESSAGE PREVIEW")
            print("=" * 70)
            print(discord_message)

        if send_gmail:
            print("\n" + "=" * 70)
            print("EMAIL MESSAGE PREVIEW")
            print("=" * 70)
            print(email_message)
            print("\n" + "=" * 70)
            print("CSV ATTACHMENTS:")
            print("=" * 70)
            for csv_file in csv_files:
                # Show proper filename (same logic as attachment)
                if csv_file.name.startswith("part-"):
                    display_name = f"{csv_file.parent.name}.csv"
                else:
                    display_name = csv_file.name
                print(f"  • {display_name}")

        print("\n" + "=" * 70)
        print("END OF DRY RUN")
        print("=" * 70)
    else:
        success_count = 0
        errors = []

        # Send to Discord
        if send_discord:
            try:
                logger.info("Sending report to Discord")
                send_to_discord(DISCORD_WEBHOOK_URL, discord_message)
                msg_len = len(discord_message)
                if msg_len > 2000:
                    num_parts = (msg_len // 1900) + 1
                    logger.info(f"Discord message sent successfully ({num_parts} parts)")
                    print(f"✓ Pesan berhasil dikirim ke Discord ({num_parts} bagian) dengan data agregasi lengkap.")
                else:
                    logger.info("Discord message sent successfully")
                    print("✓ Pesan berhasil dikirim ke Discord dengan data agregasi lengkap.")
                success_count += 1
            except Exception as e:
                error_msg = f"✗ Gagal mengirim ke Discord: {e}"
                logger.error(f"Failed to send to Discord: {e}", exc_info=True)
                print(error_msg)
                errors.append(error_msg)

        # Send to Gmail
        if send_gmail:
            try:
                logger.info(f"Sending email with {len(csv_files)} CSV attachments to {len(GMAIL_RECIPIENT_EMAILS)} recipients")
                week_info = parse_week_name(week_name)
                email_subject = f"NYC Taxi Weekly Report - {week_info['month']} {week_info['year']}, Week {week_info['week_num']}"
                send_to_gmail(
                    sender_email=GMAIL_SENDER_EMAIL,
                    sender_password=GMAIL_SENDER_PASSWORD,
                    recipient_emails=GMAIL_RECIPIENT_EMAILS,
                    subject=email_subject,
                    message=email_message,
                    csv_attachments=csv_files,
                )
                logger.info(f"Email sent successfully to {GMAIL_RECIPIENT_EMAILS}")
                print(f"✓ Email dengan {len(csv_files)} file CSV berhasil dikirim ke {len(GMAIL_RECIPIENT_EMAILS)} penerima:")
                for email in GMAIL_RECIPIENT_EMAILS:
                    print(f"  - {email}")
                print(f"\nFile CSV yang dilampirkan:")
                for csv_file in csv_files:
                    # Show proper filename (same logic as attachment)
                    if csv_file.name.startswith("part-"):
                        display_name = f"{csv_file.parent.name}.csv"
                    else:
                        display_name = csv_file.name
                    print(f"  • {display_name}")
                success_count += 1
            except Exception as e:
                error_msg = f"✗ Gagal mengirim email: {e}"
                logger.error(f"Failed to send email: {e}", exc_info=True)
                print(error_msg)
                errors.append(error_msg)

        # Summary
        logger.info(f"Report sending completed: {success_count} successful, {len(errors)} failed")
        if errors:
            logger.error(f"Errors occurred: {errors}")
        logger.info("=" * 70)
        logger.info("WEEKLY REPORT SENDER - COMPLETED")
        logger.info("=" * 70)

        print("\n" + "=" * 70)
        print(f"SUMMARY: {success_count} berhasil, {len(errors)} gagal")
        if errors:
            print("\nErrors:")
            for err in errors:
                print(f"  {err}")
        print("=" * 70)


if __name__ == "__main__":
    main()
